# Generated by Django 6.0.5 on 2026-05-14 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('capacity', models.PositiveBigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('group', models.CharField(choices=[('A', 'Group A'), ('B', 'Group B'), ('C', 'Group C'), ('D', 'Group D'), ('E', 'Group E'), ('F', 'Group F'), ('G', 'Group G'), ('H', 'Group H'), ('I', 'Group I'), ('J', 'Group J'), ('K', 'Group K'), ('L', 'Group L')], max_length=1)),
                ('manager', models.CharField(blank=True, max_length=100, null=True)),
                ('captain', models.CharField(blank=True, max_length=100, null=True)),
                ('best_world_cup_finish', models.CharField(blank=True, max_length=100, null=True)),
                ('best_world_cup_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('Group Stage', 'Group Stage'), ('Round of 32', 'Round of 32'), ('Round of 16', 'Round of 16'), ('Quarterfinals', 'Quarterfinals'), ('Semifinals', 'Semifinals'), ('Final', 'Final')], max_length=20)),
                ('kickoff_time', models.DateTimeField()),
                ('home_team_score', models.PositiveIntegerField(blank=True, null=True)),
                ('away_team_score', models.PositiveIntegerField(blank=True, null=True)),
                ('stadium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fixtures', to='predictor.stadium')),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_fixtures', to='predictor.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_fixtures', to='predictor.team')),
            ],
            options={
                'ordering': ['kickoff_time'],
            },
        ),
    ]
