# Generated by Django 6.0.5 on 2026-05-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='best_world_cup_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
