# Generated by Django 6.0.5 on 2026-06-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_alter_team_best_world_cup_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='matchday',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
