# Generated by Django 6.0.5 on 2026-06-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0004_fixture_matchday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='stage',
            field=models.CharField(choices=[('Group Stage', 'Group Stage'), ('Round of 32', 'Round of 32'), ('Round of 16', 'Round of 16'), ('Quarterfinals', 'Quarterfinals'), ('Semifinals', 'Semifinals'), ('Third Place', 'Third Place Play-Off'), ('Final', 'Final')], max_length=20),
        ),
    ]
