# Generated by Django 6.0.5 on 2026-05-29 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontoon', '0003_pontoonball_selected_by'),
        ('predictor', '0002_prediction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoonball',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='predictor.team'),
        ),
    ]
