# Generated by Django 6.0.5 on 2026-06-01 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontoon', '0004_alter_pontoonball_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoonball',
            name='busted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pontoonball',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
